-- Business Partners Tablosu Oluşturma
CREATE TABLE IF NOT EXISTS `business_partners` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `sponsor_id` varchar(20) DEFAULT NULL,
  `partner_type` enum('individual','corporate') NOT NULL,
  `payment_status` enum('pending','completed','failed','refunded') DEFAULT 'pending',
  `status` enum('pending','active','inactive','suspended') DEFAULT 'pending',
  `first_name` varchar(100) DEFAULT NULL,
  `last_name` varchar(100) DEFAULT NULL,
  `tc_no` varchar(11) DEFAULT NULL,
  `email` varchar(255) NOT NULL,
  `phone` varchar(20) NOT NULL,
  `delivery_address` text NOT NULL,
  `billing_address` text NOT NULL,
  `company_name` varchar(255) DEFAULT NULL,
  `tax_office` varchar(100) DEFAULT NULL,
  `tax_no` varchar(20) DEFAULT NULL,
  `authorized_person` varchar(200) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`),
  KEY `sponsor_id` (`sponsor_id`),
  KEY `partner_type` (`partner_type`),
  KEY `payment_status` (`payment_status`),
  KEY `status` (`status`),
  KEY `email` (`email`),
  CONSTRAINT `business_partners_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
